---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-go
  template:
    metadata:
      labels:
        app: web-go
    spec:
      containers:
      - name: web-go
        image: localhost:32000/web-go:registry
        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-go
spec:
  type: LoadBalancer
  selector:
    app: web-go
  ports:
  - port: 3333
    targetPort: 8080